[package]
name = "tokio-redis"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1"
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"

[lib]
name = "tokio_redis"
path = "src/lib.rs"